services:
  gateway:
    build: ./services/gateway
    container_name: gateway
    ports:
      - "9000:9000"
    environment:
      PORT: 9000
      GOVAULT_AUTH_SERVICE_URL: ${GOVAULT_AUTH_SERVICE_URL}
      GOVAULT_UPLOAD_SERVICE_URL: ${GOVAULT_UPLOAD_SERVICE_URL}
      GOVAULT_FILES_SERVICE_URL: ${GOVAULT_FILES_SERVICE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      FRONTEND_URL: ${FRONTEND_URL}
      BACKEND_URL: ${BACKEND_URL}
      DEV_URL: ${DEV_URL}
    depends_on:
      - auth-service
      - upload-service
      - files-service
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9000/health"]
      interval: 2m
      timeout: 2s
      retries: 5

  auth-service:
    build: ./services/auth
    container_name: auth-service
    expose:
      - "9001"
    environment:
      PORT: 9001
      AUTH_POSTGRES_URL_DEV: ${AUTH_POSTGRES_URL_DEV}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    depends_on:
      auth-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9001/health"]
      interval: 2m
      timeout: 2s
      retries: 5
  
  upload-service:
    build: ./services/upload
    container_name: upload-service
    expose:
      - "9002"
    environment:
      PORT: 9002
      GOVAULT_FILES_SERVICE_URL: ${GOVAULT_FILES_SERVICE_URL}
      UPLOAD_POSTGRES_URL_DEV: ${UPLOAD_POSTGRES_URL_DEV}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      BUCKET_NAME: ${BUCKET_NAME}
      AWS_ENDPOINT: ${AWS_ENDPOINT}
      AWS_PUBLIC_ENDPOINT: ${AWS_PUBLIC_ENDPOINT}
    depends_on:
      upload-db:
        condition: service_healthy
      minio:              
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9002/health"]
      interval: 2m
      timeout: 2s
      retries: 5   
    volumes:
      - upload_session_data:/app/sessions 

  files-service:
    build: ./services/files
    container_name: files-service
    expose:
      - "9003"
    environment:
      PORT: 9003
      FILES_POSTGRES_URL_DEV: ${FILES_POSTGRES_URL_DEV}
      GOVAULT_AUTH_SERVICE_URL: ${GOVAULT_AUTH_SERVICE_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      BUCKET_NAME: ${BUCKET_NAME}
      AWS_ENDPOINT: ${AWS_ENDPOINT}
      AWS_PUBLIC_ENDPOINT: ${AWS_PUBLIC_ENDPOINT}
      
    depends_on:
      files-db:
        condition: service_healthy
      minio:              
        condition: service_healthy      
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9003/health"]
      interval: 2m
      timeout: 2s
      retries: 5    

  # ---------- DATABASES ----------

  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${AUTH_DB_NAME} -U ${AUTH_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  upload-db:
    image: postgres:16
    container_name: upload-db
    environment:
      POSTGRES_USER: ${UPLOAD_DB_USER}
      POSTGRES_PASSWORD: ${UPLOAD_DB_PASSWORD}
      POSTGRES_DB: ${UPLOAD_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${UPLOAD_DB_NAME} -U ${UPLOAD_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - upload_db_data:/var/lib/postgresql/data
  
  files-db:
    image: postgres:16
    container_name: files-db
    environment:
      POSTGRES_USER: ${FILES_DB_USER}
      POSTGRES_PASSWORD: ${FILES_DB_PASSWORD}
      POSTGRES_DB: ${FILES_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${FILES_DB_NAME} -U ${FILES_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - files_db_data:/var/lib/postgresql/data
  
# ---------- Monitoring ----------

# ---------- Monitoring ----------

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus  # This maps the named volume to the data directory
    ports:
      - "9090:9090"
    # Optional: ensure prometheus uses the correct storage path if you change defaults
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=10d' # Keeps data for 15 days
    depends_on:
      gateway:
        condition: service_healthy

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

# ---------- Smoke Tests ----------
  smoke-tests:
    image: curlimages/curl
    depends_on:
      auth-service:
        condition: service_healthy
      upload-service:
        condition: service_healthy
      files-service:
        condition: service_healthy
      gateway:
        condition: service_healthy
      minio:
        condition: service_healthy
    command: >
      sh -c "
      curl -f http://gateway:9000/health &&
      curl -f http://auth-service:9001/health &&
      curl -f http://upload-service:9002/health &&
      curl -f http://files-service:9003/health &&
      curl -f http://minio:9000/minio/health/live
      "

# ---------- MINIO ----------
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9100:9000"  # S3 API
      - "9101:9001"  # MinIO console UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"  # temp data, no volumes
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

# Minio client , responsible for setting up bucket in minio before startup 
  minio-init:
    image: minio/mc
    container_name: minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 minioadmin minioadmin &&
      mc mb --ignore-existing local/govault-files &&
      mc anonymous set public local/govault-files  
      "
  # mc anonymous set public allows public read/write on the bucket which is fine for dev/testing.
    restart: on-failure

# ---------- VOLUMES ----------

volumes:
  auth_db_data:
  upload_db_data:
  files_db_data:
  grafana_data:  
  prometheus_data:
  upload_session_data:    # 
