services:
  gateway:
    build: ./services/gateway
    container_name: gateway
    ports:
      - "9000:9000"
    environment:
      PORT: 9000
      GOVAULT_AUTH_SERVICE_URL: ${GOVAULT_AUTH_SERVICE_URL}
      GOVAULT_UPLOAD_SERVICE_URL: ${GOVAULT_UPLOAD_SERVICE_URL}
      GOVAULT_FILES_SERVICE_URL: ${GOVAULT_FILES_SERVICE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      FRONTEND_URL: ${FRONTEND_URL}
      BACKEND_URL: ${BACKEND_URL}
      DEV_URL: ${DEV_URL}
    depends_on:
      - auth-service
      - upload-service
      - files-service
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9000/health"]
      interval: 2m
      timeout: 2s
      retries: 5

  auth-service:
    build: ./services/auth
    container_name: auth-service
    expose:
      - "9001"
    environment:
      PORT: 9001
      AUTH_POSTGRES_URL_DEV: ${AUTH_POSTGRES_URL_DEV}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    depends_on:
      auth-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9001/health"]
      interval: 2m
      timeout: 2s
      retries: 5
  
  upload-service:
    build: ./services/upload
    container_name: upload-service
    expose:
      - "9002"
    environment:
      PORT: 9002
      GOVAULT_FILES_SERVICE_URL: ${GOVAULT_FILES_SERVICE_URL}
      UPLOAD_POSTGRES_URL_DEV: ${UPLOAD_POSTGRES_URL_DEV}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      BUCKET_NAME: ${BUCKET_NAME}
    depends_on:
      upload-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9002/health"]
      interval: 2m
      timeout: 2s
      retries: 5    

  files-service:
    build: ./services/files
    container_name: files-service
    expose:
      - "9003"
    environment:
      PORT: 9003
      FILES_POSTGRES_URL_DEV: ${FILES_POSTGRES_URL_DEV}
      GOVAULT_AUTH_SERVICE_URL: ${GOVAULT_AUTH_SERVICE_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      BUCKET_NAME: ${BUCKET_NAME}
    depends_on:
      files-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9003/health"]
      interval: 2m
      timeout: 2s
      retries: 5    

  # ---------- DATABASES ----------

  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${AUTH_DB_NAME} -U ${AUTH_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  upload-db:
    image: postgres:16
    container_name: upload-db
    environment:
      POSTGRES_USER: ${UPLOAD_DB_USER}
      POSTGRES_PASSWORD: ${UPLOAD_DB_PASSWORD}
      POSTGRES_DB: ${UPLOAD_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${UPLOAD_DB_NAME} -U ${UPLOAD_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - upload_db_data:/var/lib/postgresql/data
  
  files-db:
    image: postgres:16
    container_name: files-db
    environment:
      POSTGRES_USER: ${FILES_DB_USER}
      POSTGRES_PASSWORD: ${FILES_DB_PASSWORD}
      POSTGRES_DB: ${FILES_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${FILES_DB_NAME} -U ${FILES_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - files_db_data:/var/lib/postgresql/data
  
# ---------- Monitoring ----------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      gateway:
        condition: service_healthy

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

  smoke-tests:
    image: curlimages/curl
    depends_on:
      auth-service:
        condition: service_healthy
      upload-service:
        condition: service_healthy
      files-service:
        condition: service_healthy
      gateway:
        condition: service_healthy
    command: >
      sh -c "
      curl -f http://gateway:9000/health &&
      curl -f http://auth-service:9001/health &&
      curl -f http://upload-service:9002/health &&
      curl -f http://files-service:9003/health
      "


volumes:
  auth_db_data:
  upload_db_data:
  files_db_data:
  grafana_data:  
